### ISSUE TITLE
cider-load-buffer fails with "Cannot open <nil> as a Reader"

### ISSUE THREAD

**Issue by darkleaf** [adzerk-oss/boot-cljs-repl#55]
Example project: https://github.com/darkleaf/forms/tree/cad4965c5672a011d86f970547ffe8f421e4cbe5

Steps:
1. run docker-compose up
2. press M-x cider-connect
3. enter `(start-repl)`
4. open `localhost:3000` in browser
5. cljs repl started and can eval commands
6. open `src/foo.cljs` in emacs
7. press C-c C-k ;; hotkey for cider-load-buffer
8. see exception in repl buffer

Tested Cider versions: 0.14.0, 0.15.0-SNAPSHOT

Is it a bug or my mistake?

```
java.lang.IllegalArgumentException: Cannot open <nil> as a Reader.
	at clojure.java.io$fn__9544.invokeStatic(io.clj:288)
	at clojure.java.io$fn__9544.invoke(io.clj:288)
	at clojure.java.io$fn__9446$G__9422__9453.invoke(io.clj:69)
	at clojure.java.io$reader.invokeStatic(io.clj:102)
	at clojure.java.io$reader.doInvoke(io.clj:86)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at cljs.analyzer$parse_ns$fn__4437.invoke(analyzer.cljc:3370)
	at cljs.analyzer$parse_ns.invokeStatic(analyzer.cljc:3353)
	at cljs.analyzer$parse_ns.invoke(analyzer.cljc:3332)
	at cljs.analyzer$parse_ns.invokeStatic(analyzer.cljc:3343)
	at cljs.analyzer$parse_ns.invoke(analyzer.cljc:3332)
	at cljs.closure$src_file__GT_target_file.invokeStatic(closure.clj:2503)
	at cljs.closure$src_file__GT_target_file.invoke(closure.clj:2494)
	at cljs.closure$src_file__GT_target_file.invokeStatic(closure.clj:2496)
	at cljs.closure$src_file__GT_target_file.invoke(closure.clj:2494)
	at cljs.repl$load_file$fn__8485.invoke(repl.cljc:530)
	at cljs.repl$load_file.invokeStatic(repl.cljc:527)
	at cljs.repl$load_file.invoke(repl.cljc:519)
	at cljs.repl$fn__8530$self__8532.invoke(repl.cljc:670)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at cljs.repl$wrap_self$g__8509.invoke(repl.cljc:654)
	at cljs.repl$repl_STAR_$read_eval_print__8593.invoke(repl.cljc:857)
	at cljs.repl$repl_STAR_$fn__8599$fn__8608.invoke(repl.cljc:900)
	at cljs.repl$repl_STAR_$fn__8599.invoke(repl.cljc:899)
	at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1178)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1167)
	at cljs.repl$repl_STAR_.invokeStatic(repl.cljc:861)
	at cljs.repl$repl_STAR_.invoke(repl.cljc:737)
	at cemerick.piggieback$run_cljs_repl.invokeStatic(piggieback.clj:169)
	at cemerick.piggieback$run_cljs_repl.invoke(piggieback.clj:155)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$apply.invoke(core.clj:641)
	at cemerick.piggieback$evaluate.invokeStatic(piggieback.clj:258)
	at cemerick.piggieback$evaluate.invoke(piggieback.clj:254)
	at cemerick.piggieback$load_file.invokeStatic(piggieback.clj:284)
	at cemerick.piggieback$load_file.invoke(piggieback.clj:283)
	at clojure.lang.Var.invoke(Var.java:379)
	at cemerick.piggieback$wrap_cljs_repl$fn__9101$fn__9103$fn__9104.invoke(piggieback.clj:290)
	at cemerick.piggieback$enqueue$fn__9087.invoke(piggieback.clj:246)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__1531.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
java.lang.IllegalArgumentException: Cannot open <nil> as a Reader.
	at clojure.java.io$fn__9544.invokeStatic(io.clj:288)
	at clojure.java.io$fn__9544.invoke(io.clj:288)
	at clojure.java.io$fn__9446$G__9422__9453.invoke(io.clj:69)
	at clojure.java.io$reader.invokeStatic(io.clj:102)
	at clojure.java.io$reader.doInvoke(io.clj:86)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at cljs.analyzer$parse_ns$fn__4437.invoke(analyzer.cljc:3370)
	at cljs.analyzer$parse_ns.invokeStatic(analyzer.cljc:3353)
	at cljs.analyzer$parse_ns.invoke(analyzer.cljc:3332)
	at cljs.analyzer$parse_ns.invokeStatic(analyzer.cljc:3343)
	at cljs.analyzer$parse_ns.invoke(analyzer.cljc:3332)
	at cljs.closure$src_file__GT_target_file.invokeStatic(closure.clj:2503)
	at cljs.closure$src_file__GT_target_file.invoke(closure.clj:2494)
	at cljs.closure$src_file__GT_target_file.invokeStatic(closure.clj:2496)
	at cljs.closure$src_file__GT_target_file.invoke(closure.clj:2494)
	at cljs.repl$load_file$fn__8485.invoke(repl.cljc:530)
	at cljs.repl$load_file.invokeStatic(repl.cljc:527)
	at cljs.repl$load_file.invoke(repl.cljc:519)
	at cljs.repl$fn__8530$self__8532.invoke(repl.cljc:670)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$apply.invoke(core.clj:641)
	at cljs.repl$wrap_self$g__8509.invoke(repl.cljc:654)
	at cljs.repl$repl_STAR_$read_eval_print__8593.invoke(repl.cljc:857)
	at cljs.repl$repl_STAR_$fn__8599$fn__8608.invoke(repl.cljc:900)
	at cljs.repl$repl_STAR_$fn__8599.invoke(repl.cljc:899)
	at cljs.compiler$with_core_cljs.invokeStatic(compiler.cljc:1178)
	at cljs.compiler$with_core_cljs.invoke(compiler.cljc:1167)
	at cljs.repl$repl_STAR_.invokeStatic(repl.cljc:861)
	at cljs.repl$repl_STAR_.invoke(repl.cljc:737)
	at cemerick.piggieback$run_cljs_repl.invokeStatic(piggieback.clj:169)
	at cemerick.piggieback$run_cljs_repl.invoke(piggieback.clj:155)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:650)
	at clojure.core$apply.invoke(core.clj:641)
	at cemerick.piggieback$evaluate.invokeStatic(piggieback.clj:258)
	at cemerick.piggieback$evaluate.invoke(piggieback.clj:254)
	at cemerick.piggieback$load_file.invokeStatic(piggieback.clj:284)
	at cemerick.piggieback$load_file.invoke(piggieback.clj:283)
	at clojure.lang.Var.invoke(Var.java:379)
	at cemerick.piggieback$wrap_cljs_repl$fn__9101$fn__9103$fn__9104.invoke(piggieback.clj:290)
	at cemerick.piggieback$enqueue$fn__9087.invoke(piggieback.clj:246)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__1531.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by darkleaf** [comment]
This problem is not about boot or boot-cljs-repl. It's about cljs compiler, cider, docker.

Workaround: 
```
RUN mkdir -p /Users/m_kuzmin/projects/github \
    && ln -s /usr/src/app /Users/m_kuzmin/projects/github/forms
```
